main: aaa2575_main.cpp aaa2575_Transaction_List.cpp
	g++ -std=c++11 -o aaa2575_main aaa2575_main.cpp aaa2575_Transaction_List.cpp
	./aaa2575_main

test: aaa2575_test.cpp aaa2575_Transaction_List.cpp
	g++ -std=c++11 -o aaa2575_test aaa2575_Transaction_List.cpp
	./aaa2575_test

clean:
	rm -f *.o aaa2575_main aaa2575_test
